<h4>Comments</h4>
<div id="disqus_thread"></div>
<script>
    var disqus_config = function () {
        this.page.url = "http://fsharpforfunandprofit.com{{page.url | remove: "index.html" | append: "/$$" | replace: "//$$", "/$$" | remove: "$$" | escape }}";  
        this.page.identifier = this.page.url;
    };
    (function() {  // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        
        s.src = '//fforfunandprofit.disqus.com/embed.js';
        
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
<a href="//disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>

